---
dataset:
 train:
  - /home/lavezzo/SUEPCoffea_dask/out.hdf5
 validation:
  - /home/lavezzo/SUEPCoffea_dask/out.hdf5
 test:
  - /home/lavezzo/SUEPCoffea_dask/out.hdf5

dataset_misc:
 src_folder: /path/to/source/folder
 size:
  - 33902
  - 33902
  - 33902

output:
 model: ./models
 plots: ./plots

training_pref:
 batch_size_train: 25
 batch_size_validation: 150
 max_epochs: 5
 learning_rate: 0.001
 momentum: .9
 patience: 50
 reg_strength: 0.00000000001
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 100
 names_classes:
  - 'QCD'
  - 'SUEP'
 workers: 0

inference_pref:
  samples: 300

ssd_settings:
 confidence_threshold: .01
 feature_maps:
  - phi: 13
    eta: 10
  - phi: 13
    eta: 10
 input_dimensions:
  - 1
  - 100
  - 100
 n_classes: 2
 nms: .25
 object_size: 46.
 max_distance: .1
 overlap_threshold: .5
 steps:
  - phi: 10
    eta: 10
  - phi: 5
    eta: 5
 top_k: 100
